### PR TITLE
(hopefully) solve a security issue 

### PR DESCRIPTION
**Pull request by andreamazza89**
Hi, as mentioned, I was able to retrieve your api key by providing a site that extracts query params/headers instead of the actual api url.

This is now solved by checking that the apiRequestUrl starts with the appropriate api hostname, so that the sensitive api login info is only forwarded to the api provider. An error is thrown if the apiRequestUrl starts with anything but the api provider's host name.

I have also added tfl as I need it for my project. 

Hope this is helpful. :bowtie: 

And thank you for sharing this project, very useful! 👍 😄

### CODE REVIEW

**Comment by maryrosecook** [comment]
Sorry I missed this before writing a fix myself.  Thanks a lot for the PR.

Do you want to add TFL functionality to the API?

**Comment by andreamazza89** [comment]
Hi, yes, I have added tfl to the API, should I branch off and make a pull request for that?

**Comment by maryrosecook** [comment]
Ah I think it’s out of scope, I’m afraid.  The news-summary-api is specifically for providing access to the Guardian and Aylien APIs for the news summary project.

**Comment by andreamazza89** [comment]
No problem, thank you :)

**Pull request closed without merging**
